### ISSUE TITLE
Thunderbird icon

### ISSUE THREAD

**Issue by jgandert** [numixproject/numix-icon-theme-square#14]
First of all, great work! And thanks for making it free.

I hope this is okay to write here, but one thing I'd love to see is a Thunderbird icon that's similar to the Firefox one. The current one is good, but when looking at you don't really know that it's Thunderbird.

Here's a great Material themed thunderbird icon (not square, and I assume, non-free though): https://icons8.com/icon/38697/thunderbird

**Comment by bilelmoussaoui** [comment]
This should be reported here instead https://github.com/numixproject/numix-core.
This repository is a packaging one.

**Comment by jgandert** [comment]
Sure!

**Comment by Foggalong** [comment]
[We already have one](https://raw.githubusercontent.com/numixproject/numix-core/master/icons/square/48/thunderbird-branded.svg), going by the icon name `thunderbird-branded.svg`, it's just not the default for Thunderbird because it's not as nice an icon as the unbranded version. In the same vein we have `firefox-icon-unbranded.svg` found [here](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/firefox-icon-unbranded.svg) which isn't the default for the same reason.
