### ISSUE TITLE
VS Codium Icon showing up for VS Code

### ISSUE THREAD

**Issue by tegaidogun** [numixproject/numix-icon-theme-square#45]
The latest package for Fedora was missing some icons that I wanted so I pulled the icons directly from the repository here. When I did so the icon for vscode got switched around.

![Screenshot from 2024-03-02 13-28-48](https://github.com/numixproject/numix-icon-theme-square/assets/63559796/227e69d2-6a31-49d1-834e-def3662dd4cf)

But the thing is that when I copy it from the cloned folder, it becomes this:

```
tegaidogun@CHIBUDOM ~
$ sudo cp -Rf numix-icon-theme-square/Numix-Square/ /usr/share/icons/
```

it changes from the default visual studio icon to the Codium icon:

![image](https://github.com/numixproject/numix-icon-theme-square/assets/63559796/9be2f79b-bb84-4d91-8bd0-4439d3846b46)

Is there a linking issue in the files that I am overlooking? Because in the folder I cloned directly from this repository, the the normal Visual Studio Code icon is there:

![image](https://github.com/numixproject/numix-icon-theme-square/assets/63559796/8c64bee8-2de7-4d92-bb93-0c22b85b8d93)

**Comment by palob** [comment]
Linking seems correct in the repo so to be sure you should remove the old icon theme before copying over the new files in order to avoid mislinking. We definitely changed some links a while back when we introduced dedicated icons for VSCodium and VSCode-OSS (which previously had been only present as symlinks to VSCode).

**Comment by tegaidogun** [comment]
Okay then.
